# Generated by Django 3.0.5 on 2020-05-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
