# Generated by Django 3.0.5 on 2020-05-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ablog', '0004_auto_20200514_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
